sudo: required
language: ruby
rvm: 2.4
addons:
  chrome: stable
script:
  - travis_wait bundle exec rake wax:test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
    - master
