sudo: required
language: ruby
rvm: 2.4
addons:
  chrome: stable
script:
  - mkdir collections
  - bundle exec rake wax:pagemaster authors characters kashira performances performers plays productions realia scenes tags
  - travis_wait bundle exec jekyll build
  - travis_wait bundle exec rake wax:test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  except:
    - gh-pages
    - s3
