# Main settings
title:            'The Barbara Curtis Adachi Bunraku Collection'
description:      'at C.V. Starr East Asian Library'
url:              ''
baseurl:          ''

# Build settings
source:           'src'
markdown:         kramdown
exclude:          [vendor, Gemfile*, Rakefile, spec, README*, _lib, package.json, feed.xml]
permalink:        pretty
collections_dir:  collections

# Collection settings
collections:
  authors:
    output: true
    layout: item_page
    metadata:
      source: authors.json
  characters:
    output: true
    layout: item_page
    metadata:
      source: characters.json
  images:
    output: true
    layout: image_page
    metadata:
      source: images.json
  kashira:
    output: true
    layout: item_page
    metadata:
      source: kashira.json
  performances:
    output: true
    layout: item_page
    metadata:
      source: performances.json
  performers:
    output: true
    layout: item_page
    metadata:
      source: performers.json
  plays:
    output: true
    layout: item_page
    metadata:
      source: plays.json
  productions:
    output: true
    layout: item_page
    metadata:
      source: productions.json
  scenes:
    output: true
    layout: item_page
    metadata:
      source: scenes.json
  tags:
    output: true
    layout: item_page
    metadata:
      source: tags.json
  realia:
    output: true
    layout: item_page
    metadata:
      source: realia.yml

# Search index settings
lunr_index:
  - file: 'js/lunr-index.json'
    ui:   'js/lunr-ui.js'
    collections:
      authors:
        fields: [label_eng, label_ka, plays]
      characters:
        fields: [label_eng, label_ka, label_ja, plays]
      kashira:
        fields: [label_eng, label_ka, category, plays]
      performances:
        fields: [label_eng, characters, plays, productions, scenes]
      performers:
        fields: [label_eng, label_ka, specialty]
      plays:
        fields: [label_eng, label_ka, label_ja, characters, authors, kashira]
      productions:
        fields: [label_eng, plays, performances]
      scenes:
        fields: [label_eng, label_ka, label_ja, production, play]
      tags:
        fields: [label_eng, label_ka]
      realia:
        fields: [label_eng]


# Prod Dependencies

styles:
  main:         assets/main.css
  drop-nav:     assets/drop-nav.css
  font-awesome: assets/fa/css/font-awesome.min.css

js:
  bootstrap:
    version: 4.0.0
    src: https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js
  d3:
    version: 4.13.0
    src: https://cdnjs.cloudflare.com/ajax/libs/d3/4.13.0/d3.min.js
  elasticlunr:
    version: 0.9.6
    src: https://cdnjs.cloudflare.com/ajax/libs/elasticlunr/0.9.6/elasticlunr.min.js
  jquery:
    version: 3.2.1
    src: https://code.jquery.com/jquery-3.2.1.min.js
  jquery-migrate:
    version: 3.0.0
    src: https://code.jquery.com/jquery-migrate-3.0.0.min.js
  popper:
    version: 1.12.9
    src: https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js

# Search tests

quoll:
  - page: 'search'
    terms:
      - 'oshuto'
      - 'Donald Keene'
      - '白川の安珍実は桜木親王'
      - 'Ōshūto'
