title: The Barbara Curtis Adachi Bunraku Collection
description: at C.V. Starr East Asian Library
url: ''
gh-baseurl: /ldpd-bunraku

# Build settings
markdown: kramdown
exclude: [vendor, Gemfile*, Rakefile, spec, README*, _lib, package.json, feed.xml]
permalink: pretty
collections_dir: collections
lunr_languages: true

collections:
  authors:
    output: true
    source: authors.json
    layout: item_page
    lunr_index:
      fields: [label_eng, label_ka, plays]
  characters:
    output: true
    source: characters.json
    layout: item_page
    lunr_index:
      fields: [label_eng, label_ka, label_ja, plays]
  images:
    output: true
    source: images.json
    layout: image_page
  kashira:
    output: true
    source: kashira.json
    layout: item_page
    lunr_index:
      fields: [label_eng, label_ka, category, plays]
  performances:
    output: true
    source: performances.json
    layout: item_page
    lunr_index:
      fields: [label_eng, characters, plays, productions, scenes]
  performers:
    output: true
    source: performers.json
    layout: item_page
    lunr_index:
      fields: [label_eng, label_ka, specialty]
  plays:
    output: true
    source: plays.json
    layout: item_page
    lunr_index:
      fields: [label_eng, label_ka, label_ja, characters, authors, kashira]
  productions:
    output: true
    source: productions.json
    layout: item_page
    lunr_index:
      fields: [label_eng, plays, performances]
  scenes:
    output: true
    source: scenes.json
    layout: item_page
    lunr_index:
      fields: [label_eng, label_ka, label_ja, production, play]
  tags:
    output: true
    source: tags.json
    layout: item_page
    lunr_index:
      fields: [label_eng, label_ka]
  realia:
    output: true
    source: realia.yml
    layout: item_page
    lunr_index:
      fields: [label_eng]

styles:
  main: assets/main.css
  drop-nav: assets/drop-nav.css
  font-awesome: assets/fa/css/font-awesome.min.css

js:
  bootstrap:
    version: 4.0.0
    cdn: https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js
  d3:
    version: 4.13.0
    cdn: https://cdnjs.cloudflare.com/ajax/libs/d3/4.13.0/d3.min.js
  elasticlunr:
    version: 0.9.6
    cdn: https://cdnjs.cloudflare.com/ajax/libs/elasticlunr/0.9.6/elasticlunr.min.js
  jquery:
    version: 3.2.1
    cdn: https://code.jquery.com/jquery-3.2.1.min.js
  jquery-migrate:
    version: 3.0.0
    cdn: https://code.jquery.com/jquery-migrate-3.0.0.min.js
  popper:
    version: 1.12.9
    cdn: https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js

# search tests
quoll:
  full:
    page: search
    terms: [oshuto, Donald Keene, 白川の安珍実は桜木親王, Ōshūto]
