title: The Barbara Curtis Adachi Bunraku Collection
description: at C.V. Starr East Asian Library
url: ''
baseurl: ''
gh-baseurl: /ldpd-bunraku

# Build settings
markdown: kramdown
theme: minima
exclude: [vendor, Gemfile*, Rakefile, spec, README*]
permalink: pretty
collections_dir: collections
lunr_languages: true

collections:
  authors:
    output: true
    source: authors.json
    layout: author_page
    lunr_index:
      fields: [label_eng, label_ka]
  characters:
    output: true
    source: characters.json
    layout: character_page
    lunr_index:
      fields: [label_eng, label_ka, label_ja]
  images:
    output: true
    source: images.json
    layout: image_page
  kashira:
    output: true
    source: kashira.json
    layout: kashira_page
    lunr_index:
      fields: [label_eng, label_ka, category]
  performances:
    output: true
    source: performances.json
    layout: performance_page
    lunr_index:
      fields: [label_eng]
  performers:
    output: true
    source: performers.json
    layout: performer_page
    lunr_index:
      fields: [label_eng, label_ka]
  plays:
    output: true
    source: plays.json
    layout: play_page
    lunr_index:
      fields: [label_eng, label_ka, label_ja]
  productions:
    output: true
    source: productions.json
    layout: production_page
    lunr_index:
      fields: [label_eng]
  realia:
    output: true
    lunr_index:
      fields: [label_eng]
  scenes:
    output: true
    source: scenes.json
    layout: scene_page
    lunr_index:
      fields: [label_eng, label_ka, label_ja]
  tags:
    output: true
    source: tags.json
    layout: tag_page
    lunr_index:
      fields: [label_eng, label_ka]

styles:
  main: assets/main.css
  drop-nav: assets/drop-nav.css
  font-awesome: assets/fa/css/font-awesome.min.css
  slick: //cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css
  slick-theme: //cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css

js:
  jquery:
    version: 3.2.1
    cdn: //code.jquery.com/jquery-3.2.1.min.js
  jquery-migrate:
    version: 3.0.1
    cdn:  //cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.1/jquery-migrate.min.js
  elasticlunr:
    version: 0.9.6
    cdn: //cdnjs.cloudflare.com/ajax/libs/elasticlunr/0.9.6/elasticlunr.min.js
  d3:
    version: 4.13.0
    cdn: //cdnjs.cloudflare.com/ajax/libs/d3/4.13.0/d3.min.js
  slick:
    version: 1.8.1
    cdn: https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js

# search tests
quoll:
  full:
    page: search
    terms: [oshuto, Donald Keene, 白川の安珍実は桜木親王, Ōshūto]
