title: "The Barbara Curtis Adachi Bunraku Collection"
description: "at C.V. Starr East Asian Library"
baseurl:  ""
url: ""

# Build settings
markdown: "kramdown"
theme: "minima"
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

permalink: "pretty"

styles:
  main: assets/main.css
  drop-nav: assets/drop-nav.css
  font-awesome: assets/fa/css/font-awesome.min.css
  slick: assets/slick.css
  slick-theme: assets/slick-theme.css

scripts:
  jquery: //code.jquery.com/jquery-3.2.1.min.js
  jquery-migrate: //code.jquery.com/jquery-migrate-3.0.0.min.js
  ldpd-toolkit: //cdn.cul.columbia.edu/ldpd-toolkit/widgets/cultnbw.min.js
  lunr: js/lunr.min.js # //cdnjs.cloudflare.com/ajax/libs/lunr.js/2.1.3/lunr.min.js
  lunr-unicode: js/lunr-unicode-normalizer.js
  d3-v3: //d3js.org/d3.v3.min.js
  d3-v4: //d3js.org/d3.v4.min.js
  d3-tip: js/d3.tip.js
  d3-tip-patch: js/d3-v4-patch.tip.js
  slick: js/slick.min.js # http://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js

collections:
  pages:
    output: true
  authors:
    output: true
  characters:
    output: true
  images:
    output: true
  kashira:
    output: true
  performances:
    output: true
  performers:
    output: true
  plays:
    output: true
  productions:
    output: true
  scenes:
    output: true
  realia:
    output: true
  tags:
    output: true

search_tests:
  full:
    page: search
    terms:
      - "Ōshūto"
      - "oshuto"
      - "Donald Keene"
      - "文楽のひとびと"
      - "emperor 娘お安"
